# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

matrix:
  fast_finish: true

# what combinations to test
environment:
  TEST_API_URL: https://api.balena-staging.com
  TEST_PAID_EMAIL: ''
  TEST_PAID_PASSWORD: ''
  matrix:
  - nodejs_version: 8
    TEST_EMAIL: sdk+tests+thgreasi+staging1@resin.io
    TEST_PASSWORD:
      secure: 8nN91Lv/+o9tRYPfuSinWw==
    TEST_USERNAME: sdk_tests_thgreasi_staging1
    TEST_REGISTER_EMAIL: test2+register+juan@resin.io
    TEST_REGISTER_PASSWORD:
      secure: 5q1vra242X+0xjTU5msqOQ==
    TEST_REGISTER_USERNAME: test2_register_juan
    TEST_ONLY_ON_ENVIRONMENT: node
  - nodejs_version: 8
    TEST_EMAIL: sdk+tests+thgreasi+staging2@resin.io
    TEST_PASSWORD:
      secure: ByZuAvlooMo9hgo5AvXsLg==
    TEST_USERNAME: sdk_tests_thgreasi_staging2
    TEST_REGISTER_EMAIL: sdk+tests+thgreasi+register@resin.io
    TEST_REGISTER_PASSWORD:
      secure: cjQpH4aI3I85w1La/f0uiA==
    TEST_REGISTER_USERNAME: sdk_tests_thgreasi_register
    TEST_ONLY_ON_ENVIRONMENT: browser

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@6
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test

notifications:

  - provider: Webhook
    url: https://webhooks.gitter.im/e/3d5ed28fa9ae4c25f46f
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
